version: '3.4'

services:
  t6t.gateway:
    image: ${DOCKER_REGISTRY-}t6tgateway
    build:
      context: .
      dockerfile: T6t.Gateway/Dockerfile

  t6t.authorization:
    image: ${DOCKER_REGISTRY-}t6tauthorization
    build:
      context: .
      dockerfile: T6t.Authorization/Dockerfile

